steps:
  # Phase 2: Build Docker image using Cloud Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climbing-repo/climbing-web-app-bolt",
        "--progress=plain",
        "-f",
        "Dockerfile",
        ".",
      ]
    timeout: 900s

  # Phase 2: Push Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climbing-repo/climbing-web-app-bolt",
      ]
    timeout: 600s

  # Phase 2: Deploy to Cloud Run with enhanced settings
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "climbing-web-app-bolt",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climbing-repo/climbing-web-app-bolt",
        "--platform",
        "managed",
        "--region",
        "asia-northeast1",
        "--allow-unauthenticated",
        "--port",
        "8000",
        "--memory",
        "4Gi",
        "--cpu",
        "2",
        "--max-instances",
        "10",
        "--timeout",
        "900",
        "--concurrency",
        "10",
        "--set-env-vars",
        "MEMORY_LIMIT=4096M,REQUEST_TIMEOUT=900,PHASE=2,MAX_FILE_SIZE=100MB,GCS_BUCKET_NAME=your_gcs_bucket_name,GEMINI_API_KEY=your_gemini_api_key,GOOGLE_API_KEY=your_gemini_api_key,CHROMA_DB_URL=your_chromadb_url,CHROMA_COLLECTION_NAME=bouldering_advice,EMBEDDING_MODEL=models/embedding-001,LOG_LEVEL=INFO,HTTP2_ENABLED=true,MAX_REQUEST_SIZE=104857600",
      ]
    timeout: 900s

# Phase 2: Enhanced timeout for video processing
timeout: 2400s

options:
  # Phase 2: Use high-CPU machine for video processing
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/climbing-repo/climbing-web-app-bolt"
